pipeline:
  name: bench-coalesce

nodes:
  - type: source
    name: source
    config:
      name: source
      type: csv
      path: bench://input.csv
      options:
        has_header: true
      schema:
        - { name: f0, type: int }
        - { name: f1, type: string }
        - { name: f2, type: int }

  - type: transform
    name: coalesce
    input: source
    config:
      cxl: |
        emit c0 = f0 ?? 0
        emit c1 = f1 ?? "default"
        emit c2 = f2 ?? f0 ?? -1

  - type: output
    name: sink
    input: coalesce
    config:
      name: sink
      type: csv
      path: bench://output.csv
      include_unmapped: true
