pipeline:
  name: bench-date-methods

nodes:
  - type: source
    name: source
    config:
      name: source
      type: csv
      path: bench://input.csv
      options:
        has_header: true
      schema:
        - { name: f0, type: string }
        - { name: f1, type: date }

  - type: transform
    name: dates
    input: source
    config:
      cxl: |
        emit d_year = f1.year()
        emit d_month = f1.month()
        emit d_add = f1.add_days(30)
        emit d_fmt = f1.format_date("%m/%d/%Y")

  - type: output
    name: sink
    input: dates
    config:
      name: sink
      type: csv
      path: bench://output.csv
      include_unmapped: true
