pipeline:
  name: bench-fixed-width-passthrough

nodes:
  - type: source
    name: source
    config:
      name: source
      type: fixed_width
      path: bench://input.dat
      schema:
        - { name: f0, type: int, start: 0, width: 10 }
        - { name: f1, type: string, start: 10, width: 10 }

  - type: transform
    name: passthrough
    input: source
    config:
      cxl: |
        emit f0 = f0

  - type: output
    name: sink
    input: passthrough
    config:
      name: sink
      type: fixed_width
      path: bench://output.dat
      schema:
        - { name: f0, type: int, width: 10 }
        - { name: f1, type: string, width: 10 }
      include_unmapped: true
