//! Workspace guard: every production `MemoryConsumer` is listed, classified
//! and tabled.
//!
//! The contract: every production implementation of `MemoryConsumer` in the
//! workspace appears in [`MANIFEST`] with its spill class and the row of the
//! per-operator arbitration-parameters table in
//! `docs/engine/src/memory-arbitration.md` that its `spill_priority` and
//! `can_back_pressure` follow. A new consumer fails this test until someone
//! answers the Memory budget checklist in `docs/ai/32_NODE_OBLIGATIONS.md`
//! for it: which row it takes (adding the row in the same change), and
//! whether its state spills.
//!
//! A consumer whose `try_spill` frees nothing is [`SpillClass::ChargedOnly`]
//! and names the approval that allows it. A new charged-only entry needs the
//! maintainer's recorded approval; the pre-existing ones say they pre-date
//! this contract, so they are not precedent for another.
//!
//! Registering with the arbitrator is a call a consumer makes, not something
//! the compiler enforces, so this scan is what makes a new consumer visible in
//! review rather than only in a later memory incident.
//!
//! # What this scan cannot see
//!
//! It matches text, not syntax, so the gaps are named here:
//!
//! - **An impl split across lines.** Only a line that starts at column 0 with
//!   `impl` and contains `MemoryConsumer for ` is recognized; an
//!   `impl MemoryConsumer` whose `for <Type>` sits on the next line is missed.
//! - **An impl generated by a macro.** The expansion is not in the source
//!   text.
//! - **A consumer that is never registered.** The scan proves an
//!   implementation is listed, not that any code path registers it with the
//!   arbitrator, nor that state which should be a consumer implements the
//!   trait at all.
//! - **Test-only implementations are skipped by location.** An indented impl
//!   (the usual in-file `#[cfg(test)] mod tests`), a file under
//!   `src/executor/tests/`, a file named `tests.rs`, and the `tests/` and
//!   `benches/` trees of every crate are not scanned. A test fixture placed
//!   anywhere else at column 0 reads as a production consumer and fails the
//!   test loudly rather than hiding.
//! - **Only `<workspace>/crates` is walked.** An implementation outside that
//!   tree is invisible here.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

/// Whether a consumer's state can leave memory when the arbitrator asks.
enum SpillClass {
    /// `try_spill` (or the spill request it posts) moves resident state to
    /// disk.
    Spillable,
    /// Charged to the ledger but never freed by a spill. `approval` names the
    /// recorded maintainer approval, or states that the consumer pre-dates
    /// this contract.
    ChargedOnly { approval: &'static str },
}

/// One production `MemoryConsumer` implementation.
struct ManifestEntry {
    /// The implementing type's name, as it appears after `for`.
    name: &'static str,
    class: SpillClass,
    /// The full first-cell text of the consumer's row in the per-operator
    /// arbitration-parameters table, trimmed, backticks included.
    table_row: &'static str,
}

/// Every production `MemoryConsumer` in the workspace.
const MANIFEST: &[ManifestEntry] = &[
    ManifestEntry {
        name: "NodeBufferConsumer",
        class: SpillClass::Spillable,
        table_row: "`node_buffers` slot (inter-stage buffer)",
    },
    ManifestEntry {
        name: "GraceHashConsumer",
        class: SpillClass::Spillable,
        table_row: "grace-hash Combine",
    },
    ManifestEntry {
        name: "ReshapeConsumer",
        class: SpillClass::Spillable,
        table_row: "Reshape",
    },
    ManifestEntry {
        name: "SortConsumer",
        class: SpillClass::Spillable,
        table_row: "sort buffer / IEJoin build",
    },
    ManifestEntry {
        name: "SortMergeConsumer",
        class: SpillClass::Spillable,
        table_row: "sort-merge Combine",
    },
    ManifestEntry {
        name: "AggregateConsumer",
        class: SpillClass::Spillable,
        table_row: "hash Aggregate",
    },
    ManifestEntry {
        name: "CullConsumer",
        class: SpillClass::Spillable,
        table_row: "Cull",
    },
    ManifestEntry {
        name: "CombineHashConsumer",
        class: SpillClass::ChargedOnly {
            approval: "maintainer approval 2026-09-25: the inline hash join's build side is \
                       never spilled; grace-hash is the spillable join strategy",
        },
        table_row: "inline-hash Combine",
    },
    ManifestEntry {
        name: "CredentialRegistryConsumer",
        class: SpillClass::ChargedOnly {
            approval: "maintainer approval 2026-09-25: credentials are never written to disk",
        },
        table_row: "credential registry",
    },
    ManifestEntry {
        name: "TransientNodeBufferConsumer",
        class: SpillClass::ChargedOnly {
            approval: "pre-dates the contract; engine table row: transient scan materialization",
        },
        table_row: "transient scan materialization",
    },
    ManifestEntry {
        name: "ArenaConsumer",
        class: SpillClass::ChargedOnly {
            approval: "pre-dates the contract; engine table row: window arena",
        },
        table_row: "window arena",
    },
    ManifestEntry {
        name: "SourceConsumer",
        class: SpillClass::ChargedOnly {
            approval: "pre-dates the contract; pauses its reader instead of spilling",
        },
        table_row: "Source ingest",
    },
    ManifestEntry {
        name: "WriterResourceConsumer",
        class: SpillClass::ChargedOnly {
            approval: "pre-dates the contract; spills only its fixed staging tails",
        },
        table_row: "output staging (writer resources)",
    },
];

/// The engine document holding the per-operator table, relative to the
/// workspace root.
const ENGINE_DOC: &str = "docs/engine/src/memory-arbitration.md";

/// The heading directly above the per-operator table.
const TABLE_HEADING: &str = "### Per-operator arbitration parameters";

/// Workspace root, derived from this crate's manifest directory.
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("clinker-exec lives at <workspace>/crates/clinker-exec")
        .to_path_buf()
}

/// Is `relative` (a path relative to the workspace root) a production source
/// file this scan covers?
///
/// It must sit under some crate's `src` tree, and not in a location reserved
/// for tests: `src/executor/tests/`, a file named `tests.rs`, or a crate's
/// `tests/` or `benches/` directory.
fn is_production_source(relative: &Path) -> bool {
    let parts: Vec<&str> = relative
        .components()
        .filter_map(|component| match component {
            Component::Normal(part) => part.to_str(),
            _ => None,
        })
        .collect();
    // crates/<crate>/<top>/...
    let [first, _crate_name, top, ..] = parts.as_slice() else {
        return false;
    };
    if *first != "crates" || *top == "tests" || *top == "benches" {
        return false;
    }
    if !parts.contains(&"src") {
        return false;
    }
    if parts.last().is_some_and(|name| *name == "tests.rs") {
        return false;
    }
    !parts
        .windows(3)
        .any(|window| window == ["src", "executor", "tests"])
}

/// Every production `.rs` file under `<workspace>/crates`, as workspace-relative
/// paths, sorted.
fn production_sources(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.join("crates")];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if path.is_dir() {
                // Build outputs hold generated sources that are not part of
                // the contract, and are large enough to matter for runtime.
                if name.starts_with("target") || name == ".git" {
                    continue;
                }
                stack.push(path);
            } else if name.ends_with(".rs") {
                let relative = path
                    .strip_prefix(root)
                    .expect("walked paths live under the workspace root")
                    .to_path_buf();
                if is_production_source(&relative) {
                    out.push(relative);
                }
            }
        }
    }
    out.sort();
    out
}

/// The implementing type named by a column-0 `impl … MemoryConsumer for <Type>`
/// line, or `None` for any other line.
///
/// The name runs from after `for ` to the first character that is not
/// alphanumeric or `_`, so generic arguments and the opening brace are
/// dropped.
fn impl_target(line: &str) -> Option<&str> {
    const NEEDLE: &str = "MemoryConsumer for ";
    if !line.starts_with("impl") {
        return None;
    }
    let after = &line[line.find(NEEDLE)? + NEEDLE.len()..];
    let end = after
        .find(|c: char| !(c.is_alphanumeric() || c == '_'))
        .unwrap_or(after.len());
    let name = &after[..end];
    (!name.is_empty()).then_some(name)
}

/// Every `MemoryConsumer` implementation in `text`, as `(1-based line, type)`.
fn consumer_impls(text: &str) -> Vec<(usize, String)> {
    text.lines()
        .enumerate()
        .filter_map(|(index, line)| impl_target(line).map(|name| (index + 1, name.to_owned())))
        .collect()
}

/// The trimmed first cell of every data row of the per-operator table in
/// `doc`: the lines from the table's header row to the first non-table line
/// after it, skipping the header and its separator.
fn table_first_cells(doc: &str) -> Result<Vec<String>, String> {
    let mut lines = doc.lines();
    lines
        .by_ref()
        .find(|line| line.trim() == TABLE_HEADING)
        .ok_or_else(|| format!("no `{TABLE_HEADING}` heading"))?;
    let mut table = lines
        .skip_while(|line| !line.trim_start().starts_with('|'))
        .take_while(|line| line.trim_start().starts_with('|'));
    table
        .next()
        .ok_or_else(|| format!("no table under `{TABLE_HEADING}`"))?;
    let cells: Vec<String> = table
        .filter(|row| {
            !row.chars()
                .all(|c| matches!(c, '|' | '-' | ':' | ' ' | '\t'))
        })
        .filter_map(|row| {
            row.trim()
                .strip_prefix('|')
                .and_then(|rest| rest.split('|').next())
                .map(|cell| cell.trim().to_owned())
        })
        .collect();
    if cells.is_empty() {
        return Err(format!(
            "the table under `{TABLE_HEADING}` has no data rows"
        ));
    }
    Ok(cells)
}

/// How many first cells equal `table_row` exactly. A manifest entry passes
/// only when this is one.
fn rows_matching(cells: &[String], table_row: &str) -> usize {
    cells
        .iter()
        .filter(|cell| cell.as_str() == table_row)
        .count()
}

#[test]
fn every_memory_consumer_is_in_the_manifest() {
    let root = workspace_root();
    let mut found: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for relative in production_sources(&root) {
        let text = std::fs::read_to_string(root.join(&relative))
            .unwrap_or_else(|error| panic!("read {}: {error}", relative.display()));
        for (line, name) in consumer_impls(&text) {
            found
                .entry(name)
                .or_default()
                .push(format!("{}:{line}", relative.display()));
        }
    }

    let mut listed = BTreeSet::new();
    let mut duplicates = Vec::new();
    for entry in MANIFEST {
        if !listed.insert(entry.name) {
            duplicates.push(entry.name);
        }
    }

    let mut report = String::new();
    for (name, sites) in &found {
        if !listed.contains(name.as_str()) {
            for site in sites {
                writeln!(
                    report,
                    "unlisted MemoryConsumer `{name}` at {site}: answer the Memory budget \
                     checklist in docs/ai/32_NODE_OBLIGATIONS.md and add it to MANIFEST"
                )
                .unwrap();
            }
        }
    }
    for name in &listed {
        if !found.contains_key(*name) {
            writeln!(
                report,
                "stale manifest entry `{name}`: no production `impl MemoryConsumer for {name}` \
                 remains; remove the entry"
            )
            .unwrap();
        }
    }
    for name in duplicates {
        writeln!(report, "manifest lists `{name}` more than once").unwrap();
    }
    assert!(report.is_empty(), "\n{report}");
}

#[test]
fn every_manifest_entry_names_an_engine_table_row() {
    let doc = std::fs::read_to_string(workspace_root().join(ENGINE_DOC))
        .unwrap_or_else(|error| panic!("read {ENGINE_DOC}: {error}"));
    let cells = table_first_cells(&doc).unwrap_or_else(|error| panic!("{ENGINE_DOC}: {error}"));

    let mut report = String::new();
    for entry in MANIFEST {
        let matches = rows_matching(&cells, entry.table_row);
        if matches != 1 {
            writeln!(
                report,
                "`{}` names table row \"{}\", which matches {matches} first cells of the \
                 per-operator table in {ENGINE_DOC}; it must equal exactly one",
                entry.name, entry.table_row
            )
            .unwrap();
        }
    }
    assert!(report.is_empty(), "\n{report}");
}

#[test]
fn charged_only_entries_cite_an_approval() {
    let unapproved: Vec<&str> = MANIFEST
        .iter()
        .filter_map(|entry| match entry.class {
            SpillClass::ChargedOnly { approval } if approval.trim().is_empty() => Some(entry.name),
            SpillClass::ChargedOnly { .. } | SpillClass::Spillable => None,
        })
        .collect();
    assert!(
        unapproved.is_empty(),
        "charged-only consumers without an approval: {unapproved:?}"
    );
}

#[test]
fn impl_matcher_reads_column_zero_impls_only() {
    let text = "\
impl MemoryConsumer for Extra {
impl crate::pipeline::memory::MemoryConsumer for Qualified {
impl<T: Send> MemoryConsumer for Generic<T> {
    impl MemoryConsumer for Indented {
// impl MemoryConsumer for Commented {
impl MemoryConsumerFactory for NotAConsumer {
impl Drop for Extra {
";
    assert_eq!(
        consumer_impls(text),
        vec![
            (1, "Extra".to_owned()),
            (2, "Qualified".to_owned()),
            (3, "Generic".to_owned()),
        ]
    );
}

#[test]
fn row_matcher_requires_the_whole_first_cell() {
    let doc = "\
## Earlier

| Unrelated | table |
|-----------|-------|
| Reshape | 1 |

### Per-operator arbitration parameters

Prose above the table.

| Operator class | `spill_priority` | `can_back_pressure` |
|----------------|------------------|---------------------|
| `node_buffers` slot (inter-stage buffer) | 0 | false |
| hash Aggregate | 30 | false |
| window arena | last | Reshape |

| Later | table |
|-------|-------|
| Cull | 1 |
";
    let cells = table_first_cells(doc).expect("the synthetic table parses");
    assert_eq!(
        cells,
        vec![
            "`node_buffers` slot (inter-stage buffer)".to_owned(),
            "hash Aggregate".to_owned(),
            "window arena".to_owned(),
        ]
    );
    assert_eq!(
        rows_matching(&cells, "`node_buffers` slot (inter-stage buffer)"),
        1
    );
    // A prefix of a cell is not the cell.
    assert_eq!(rows_matching(&cells, "`node_buffers` slot"), 0);
    assert_eq!(rows_matching(&cells, "hash"), 0);
    // Text that appears only in a later column, or only in another table.
    assert_eq!(rows_matching(&cells, "Reshape"), 0);
    assert_eq!(rows_matching(&cells, "Cull"), 0);
    assert!(table_first_cells("### Some other heading\n\n| a | b |\n").is_err());
}

#[test]
fn production_source_filter_skips_test_trees() {
    let covered = [
        "crates/clinker-exec/src/executor/node_buffer.rs",
        "crates/clinker/src/credential_profile.rs",
        "crates/clinker-exec/src/pipeline/grace_hash/mod.rs",
    ];
    let skipped = [
        "crates/clinker-exec/src/executor/tests/source_pause_liveness.rs",
        "crates/clinker-exec/src/pipeline/grace_hash/tests.rs",
        "crates/clinker-exec/tests/arbitration_hard_limit_overshoot.rs",
        "crates/clinker-exec/tests/common/dlq_sink.rs",
        "crates/clinker-exec/benches/arbitration_poll.rs",
        "crates/clinker-exec/build.rs",
        "docs/engine/src/memory-arbitration.rs",
    ];
    for path in covered {
        assert!(is_production_source(Path::new(path)), "{path} is covered");
    }
    for path in skipped {
        assert!(!is_production_source(Path::new(path)), "{path} is skipped");
    }
}
