//! Byte-level emit helpers shared by the scenario generators.
//!
//! Everything here builds a `String` that the caller converts to bytes, and
//! every line terminator is an explicit `\n`. Nothing uses `println!` or any
//! platform-dependent newline: `.gitattributes` forces `eol=lf` repo-wide
//! precisely so byte-compared goldens survive a Windows checkout, and a
//! generator that emitted `\r\n` would defeat that on the input side.
//!
//! Money is formatted from integer cents. No `f64` reaches a generated byte, so
//! a golden never depends on float formatting behaviour.

use chrono::{Duration, NaiveDate};

/// Fixed origin for every generated date.
///
/// Scenario data must be identical on every run and every machine, so no
/// generator may consult the wall clock. Dates are offsets from this constant.
pub const EPOCH: NaiveDate = match NaiveDate::from_ymd_opt(2026, 1, 5) {
    Some(d) => d,
    None => panic!("EPOCH is a valid calendar date"),
};

/// A date `days` after [`EPOCH`], as `YYYY-MM-DD`.
pub fn day(days: i64) -> String {
    (EPOCH + Duration::days(days))
        .format("%Y-%m-%d")
        .to_string()
}

/// A timestamp `days` after [`EPOCH`] at the given time, as RFC 3339 UTC.
pub fn timestamp(days: i64, hour: u32, minute: u32, second: u32) -> String {
    let d = EPOCH + Duration::days(days);
    format!(
        "{}T{hour:02}:{minute:02}:{second:02}Z",
        d.format("%Y-%m-%d")
    )
}

/// Integer cents rendered as a fixed two-decimal amount (`2450` -> `24.50`).
///
/// Negative values keep the sign ahead of the whole part.
pub fn money(cents: i64) -> String {
    let sign = if cents < 0 { "-" } else { "" };
    let abs = cents.unsigned_abs();
    format!("{sign}{}.{:02}", abs / 100, abs % 100)
}

/// Append one CSV record, quoting only fields that require it.
///
/// A field is quoted when it contains the delimiter, a double quote, CR, or LF;
/// embedded quotes are doubled. Fields that need no quoting are written bare so
/// the generated file reads like something a real system exported.
pub fn csv_row(out: &mut String, fields: &[&str]) {
    for (i, f) in fields.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        if f.contains([',', '"', '\n', '\r']) {
            out.push('"');
            for ch in f.chars() {
                if ch == '"' {
                    out.push('"');
                }
                out.push(ch);
            }
            out.push('"');
        } else {
            out.push_str(f);
        }
    }
    out.push('\n');
}

/// Escape text for an XML element body or attribute value.
///
/// Escapes the five predefined entities. Attribute values and element text are
/// escaped identically here — over-escaping `'` and `"` in element text is
/// well-formed and keeps one code path.
pub fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Append a leaf XML element with escaped text at the given indent depth.
pub fn xml_leaf(out: &mut String, depth: usize, name: &str, text: &str) {
    for _ in 0..depth {
        out.push_str("  ");
    }
    out.push('<');
    out.push_str(name);
    out.push('>');
    out.push_str(&xml_escape(text));
    out.push_str("</");
    out.push_str(name);
    out.push_str(">\n");
}

/// Escape a string for inclusion in a JSON document.
///
/// Handles the two mandatory escapes plus the C0 control range; the generated
/// vocabulary contains no control characters, but a generator that grows one
/// later should not silently emit invalid JSON.
pub fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csv_row_quotes_only_when_required() {
        let mut s = String::new();
        csv_row(&mut s, &["plain", "has,comma", "has\"quote", "trailing"]);
        assert_eq!(s, "plain,\"has,comma\",\"has\"\"quote\",trailing\n");
    }

    #[test]
    fn csv_row_always_terminates_with_lf() {
        // Guards the .gitattributes eol=lf contract from the input side.
        let mut s = String::new();
        csv_row(&mut s, &["a"]);
        assert!(s.ends_with('\n') && !s.contains('\r'));
    }

    #[test]
    fn money_renders_integer_cents_without_floats() {
        assert_eq!(money(2450), "24.50");
        assert_eq!(money(5), "0.05");
        assert_eq!(money(100), "1.00");
        assert_eq!(money(-2450), "-24.50");
        // The classic float-formatting trap: 0.1 + 0.2 style drift cannot occur
        // because no division by 100.0 ever happens.
        assert_eq!(money(3), "0.03");
    }

    #[test]
    fn dates_are_pure_offsets_from_a_fixed_epoch() {
        assert_eq!(day(0), "2026-01-05");
        assert_eq!(day(31), "2026-02-05");
        assert_eq!(timestamp(1, 9, 30, 0), "2026-01-06T09:30:00Z");
    }

    #[test]
    fn xml_escape_covers_the_five_predefined_entities() {
        assert_eq!(
            xml_escape(r#"a<b>c&d"e'f"#),
            "a&lt;b&gt;c&amp;d&quot;e&apos;f"
        );
    }

    #[test]
    fn json_escape_handles_quotes_backslashes_and_controls() {
        assert_eq!(json_escape("a\"b\\c\nd"), "a\\\"b\\\\c\\nd");
        assert_eq!(json_escape("\u{1}"), "\\u0001");
    }
}
