//! Deterministic generator for the runnable scenario corpus under
//! `examples/scenarios/`.
//!
//! # What this crate is for
//!
//! Each scenario is a realistic end-to-end pipeline that serves two purposes at
//! once: a worked example a reader can copy, and an executed test gate. Its
//! *input* files are generated here and git-ignored; its *expected output* is
//! committed. That split is deliberate — a golden is a reviewed assertion about
//! behaviour, whereas input data is reproducible bytes with nothing to review.
//!
//! # The coupling this creates, and how it is contained
//!
//! A committed golden is only meaningful for the exact input that produced it.
//! If a generator changes and a golden does not, the pair silently stops
//! describing anything. Two mechanisms guard that:
//!
//! - [`GENERATOR_VERSION`] is bumped by any change to generated bytes.
//! - [`GeneratedData::digest`] fingerprints the generated input, and the
//!   scenario harness asserts the digest *before* comparing a single output
//!   byte. Drift therefore fails as "the input changed", not as a confusing
//!   diff against stale expectations.
//!
//! # Determinism rules every generator obeys
//!
//! - Randomness comes only from `fastrand::Rng::with_seed`, the workspace
//!   convention. Wyrand is stable within `fastrand` 2.x.
//! - No wall clock. Dates are offsets from [`emit::EPOCH`].
//! - No `HashMap` iteration; output order is positional.
//! - No floats in generated values — money is integer cents (see [`emit::money`]).
//! - Line terminators are explicit `\n`.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub mod emit;
pub mod scenarios;
pub mod vocab;

/// Version of the generated-byte contract.
///
/// Bump this for **any** change that alters a generated byte: a new field, a
/// reordered column, an edited [`vocab`] table, a different seed, or a
/// `fastrand` major upgrade. Bumping invalidates every cached input and forces
/// regeneration, which in turn surfaces the goldens that need re-blessing.
///
/// v2 moved every index draw off `fastrand`'s pointer-width-dependent `usize`
/// methods onto `u32`, so generated bytes are identical on 32- and 64-bit
/// targets rather than only within one word size. v3 reshaped the product feed:
/// money as integer minor units and repeats as direct children of the record.
pub const GENERATOR_VERSION: u32 = 3;

/// Filename of the sidecar recording what is currently materialised on disk.
///
/// Written next to the generated inputs. It is metadata about the cache, never
/// an input itself, and never contributes to the digest.
pub const META_FILE: &str = ".scenario-meta.json";

/// One generated input file, relative to a scenario's `data/` directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the scenario's `data/` directory, e.g. `orders.csv`.
    pub path: &'static str,
    /// Complete file contents.
    pub bytes: Vec<u8>,
}

/// The full generated input set for one scenario.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedData {
    files: Vec<GeneratedFile>,
}

impl GeneratedData {
    /// Wrap a generator's output, sorting by path so the digest is independent
    /// of the order a generator happened to push its files.
    pub fn new(mut files: Vec<GeneratedFile>) -> Self {
        files.sort_by_key(|f| f.path);
        Self { files }
    }

    /// The generated files, ordered by path.
    pub fn files(&self) -> &[GeneratedFile] {
        &self.files
    }

    /// Stable fingerprint of the generated input.
    ///
    /// Covers [`GENERATOR_VERSION`] and, for every file in path order, the path
    /// and its bytes. Lengths are mixed in ahead of each field so that no two
    /// distinct file sets can produce the same byte stream by concatenation.
    pub fn digest(&self) -> String {
        let mut h = blake3::Hasher::new();
        h.update(&GENERATOR_VERSION.to_le_bytes());
        h.update(&(self.files.len() as u64).to_le_bytes());
        for f in &self.files {
            h.update(&(f.path.len() as u64).to_le_bytes());
            h.update(f.path.as_bytes());
            h.update(&(f.bytes.len() as u64).to_le_bytes());
            h.update(&f.bytes);
        }
        h.finalize().to_hex().to_string()
    }
}

/// A scenario's generator entry.
pub struct Scenario {
    /// Directory name under `examples/scenarios/`, e.g. `01-storefront-orders`.
    pub id: &'static str,
    /// One-line description, shown by the binary's `list` output.
    pub summary: &'static str,
    /// Pure generator: same output on every call, on every machine.
    pub generate: fn() -> GeneratedData,
}

/// Every scenario, in ladder order.
///
/// An entry here must have a matching directory under `examples/scenarios/`
/// and a gate in the scenario harness — `gen` writes into `<id>/data/`, so a
/// registered scenario with no directory would materialise input for a
/// pipeline that does not exist. `every_registered_scenario_has_a_gate` in the
/// harness enforces the second half.
pub const REGISTRY: &[Scenario] = &[
    Scenario {
        id: "01-storefront-orders",
        summary: "CSV order export: derive line totals, drop cancellations, write a clean CSV",
        generate: scenarios::storefront_orders,
    },
    Scenario {
        id: "02-product-feed-normalize",
        summary: "XML supplier feed: flatten nested products, carry repeated categories as a multi-value column",
        generate: scenarios::product_feed,
    },
    Scenario {
        id: "03-support-triage",
        summary: "Helpdesk export: normalise priorities, route to three sinks, dead-letter unparseable rows",
        generate: scenarios::support_triage,
    },
];

/// Look up a scenario by directory id.
pub fn scenario(id: &str) -> Option<&'static Scenario> {
    REGISTRY.iter().find(|s| s.id == id)
}

/// What [`materialize`] did, so callers can report it without re-stat-ing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Materialized {
    /// Files were written.
    Written,
    /// Every file was already present with a matching digest.
    UpToDate,
}

/// Write a scenario's generated input into `dir`, creating it if needed.
///
/// Reuses what is on disk when the sidecar records a matching digest and every
/// file is present, unless `force` is set. Each file is written to a
/// process-and-thread-unique temporary name and renamed into place, so two
/// concurrent generations cannot interleave a partial file; last writer wins,
/// which is safe because the content is a pure function of the version and id.
pub fn materialize(data: &GeneratedData, dir: &Path, force: bool) -> io::Result<Materialized> {
    let digest = data.digest();
    if !force && is_up_to_date(data, dir, &digest) {
        return Ok(Materialized::UpToDate);
    }

    fs::create_dir_all(dir)?;
    for f in &data.files {
        let target = dir.join(f.path);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        write_atomic(&target, &f.bytes)?;
    }

    let meta = format!(
        "{{\n  \"generator_version\": {GENERATOR_VERSION},\n  \"digest\": \"{digest}\"\n}}\n"
    );
    write_atomic(&dir.join(META_FILE), meta.as_bytes())?;
    Ok(Materialized::Written)
}

/// Whether `dir` already holds exactly this generated input.
fn is_up_to_date(data: &GeneratedData, dir: &Path, digest: &str) -> bool {
    let Ok(raw) = fs::read_to_string(dir.join(META_FILE)) else {
        return false;
    };
    let Ok(parsed) = serde_json::from_str::<serde_json::Value>(&raw) else {
        return false;
    };
    if parsed.get("digest").and_then(|d| d.as_str()) != Some(digest) {
        return false;
    }
    // A matching sidecar is not enough. It records the digest of what was
    // *generated*, not what is on disk now, so a hand-edited input still has a
    // matching sidecar. Comparing content — not merely length — is what makes
    // `gen` able to restore a corpus a reader edited while experimenting: a
    // length-preserving edit (a status flipped, a country code swapped, one
    // digit of a price changed) is exactly the kind a byte-count check waves
    // through, and the scenario would then run against mutated input having
    // just been told it was up to date. Scenario inputs are a few KB, so
    // reading them back costs nothing worth optimising.
    data.files.iter().all(|f| {
        fs::read(dir.join(f.path))
            .map(|on_disk| on_disk == f.bytes)
            .unwrap_or(false)
    })
}

/// Write `bytes` to `path` via a unique temporary file plus rename.
fn write_atomic(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let parent = path.parent().unwrap_or(Path::new("."));
    let stem = path.file_name().and_then(|s| s.to_str()).unwrap_or("tmp");
    let tmp: PathBuf = parent.join(format!(
        ".{stem}.tmp.{}.{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    fs::write(&tmp, bytes)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = fs::remove_file(&tmp);
            Err(e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_scenario_generates_identical_bytes_on_repeat_calls() {
        // The core determinism contract. If this fails, every committed golden
        // for the affected scenario is meaningless.
        for s in REGISTRY {
            let a = (s.generate)();
            let b = (s.generate)();
            assert_eq!(a, b, "scenario {} is not deterministic", s.id);
            assert_eq!(a.digest(), b.digest(), "scenario {} digest drifted", s.id);
        }
    }

    #[test]
    fn scenario_ids_are_unique() {
        // A duplicate id would make `scenario()` resolve to the first match and
        // silently shadow the other generator.
        let mut ids: Vec<_> = REGISTRY.iter().map(|s| s.id).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(before, ids.len(), "duplicate scenario id in REGISTRY");
    }

    #[test]
    fn distinct_scenarios_have_distinct_digests() {
        // Guards against a copy-paste generator that silently produces another
        // scenario's data.
        let mut seen: Vec<(&str, String)> = Vec::new();
        for s in REGISTRY {
            let d = (s.generate)().digest();
            if let Some((other, _)) = seen.iter().find(|(_, prev)| *prev == d) {
                panic!("scenarios {} and {} generate identical data", other, s.id);
            }
            seen.push((s.id, d));
        }
    }

    #[test]
    fn generated_files_contain_no_carriage_returns() {
        // .gitattributes forces eol=lf for byte-compared fixtures; a generator
        // emitting CRLF would break golden comparison on a Windows checkout.
        for s in REGISTRY {
            for f in (s.generate)().files() {
                assert!(
                    !f.bytes.contains(&b'\r'),
                    "scenario {} file {} contains CR",
                    s.id,
                    f.path
                );
            }
        }
    }

    #[test]
    fn digest_is_order_independent_but_content_sensitive() {
        let a = GeneratedData::new(vec![
            GeneratedFile {
                path: "b.csv",
                bytes: b"two\n".to_vec(),
            },
            GeneratedFile {
                path: "a.csv",
                bytes: b"one\n".to_vec(),
            },
        ]);
        let b = GeneratedData::new(vec![
            GeneratedFile {
                path: "a.csv",
                bytes: b"one\n".to_vec(),
            },
            GeneratedFile {
                path: "b.csv",
                bytes: b"two\n".to_vec(),
            },
        ]);
        assert_eq!(
            a.digest(),
            b.digest(),
            "push order must not affect the digest"
        );

        let c = GeneratedData::new(vec![
            GeneratedFile {
                path: "a.csv",
                bytes: b"one\n".to_vec(),
            },
            GeneratedFile {
                path: "b.csv",
                bytes: b"TWO\n".to_vec(),
            },
        ]);
        assert_ne!(
            a.digest(),
            c.digest(),
            "content change must move the digest"
        );
    }

    #[test]
    fn digest_separates_fields_so_concatenation_cannot_collide() {
        // Without length prefixes, ("ab","c") and ("a","bc") would hash alike.
        let a = GeneratedData::new(vec![GeneratedFile {
            path: "ab",
            bytes: b"c".to_vec(),
        }]);
        let b = GeneratedData::new(vec![GeneratedFile {
            path: "a",
            bytes: b"bc".to_vec(),
        }]);
        assert_ne!(a.digest(), b.digest());
    }

    #[test]
    fn materialize_writes_then_reports_up_to_date() {
        let tmp = tempfile::tempdir().unwrap();
        let data = (REGISTRY[0].generate)();
        let dir = tmp.path().join("data");

        assert_eq!(
            materialize(&data, &dir, false).unwrap(),
            Materialized::Written
        );
        for f in data.files() {
            assert_eq!(fs::read(dir.join(f.path)).unwrap(), f.bytes);
        }
        assert_eq!(
            materialize(&data, &dir, false).unwrap(),
            Materialized::UpToDate
        );
        assert_eq!(
            materialize(&data, &dir, true).unwrap(),
            Materialized::Written
        );
    }

    #[test]
    fn materialize_regenerates_when_an_input_was_deleted_by_hand() {
        // A matching sidecar alone must not be trusted, or a hand-deleted input
        // would surface as a confusing read error at pipeline run time.
        let tmp = tempfile::tempdir().unwrap();
        let data = (REGISTRY[0].generate)();
        let dir = tmp.path().join("data");
        materialize(&data, &dir, false).unwrap();

        fs::remove_file(dir.join(data.files()[0].path)).unwrap();
        assert_eq!(
            materialize(&data, &dir, false).unwrap(),
            Materialized::Written
        );
        assert!(dir.join(data.files()[0].path).exists());
    }

    #[test]
    fn materialize_regenerates_after_a_length_preserving_edit() {
        // The case a byte-count check waves through. A reader experimenting with
        // the corpus edits an input in place — same length, different content —
        // and expects `gen` to restore it. Validating by length alone would
        // report "up to date", leave the mutation in place, and the scenario
        // would then fail its golden immediately after the tool asserted the
        // input was correct.
        let tmp = tempfile::tempdir().unwrap();
        let data = (REGISTRY[0].generate)();
        let dir = tmp.path().join("data");
        materialize(&data, &dir, false).unwrap();

        let target = dir.join(data.files()[0].path);
        let mut mutated = fs::read(&target).unwrap();
        let pos = mutated
            .iter()
            .position(|b| *b == b'p')
            .expect("generated CSV contains a 'p'");
        mutated[pos] = b'q';
        assert_eq!(mutated.len(), data.files()[0].bytes.len());
        fs::write(&target, &mutated).unwrap();

        assert_eq!(
            materialize(&data, &dir, false).unwrap(),
            Materialized::Written,
            "a same-length edit must not be mistaken for an up-to-date input"
        );
        assert_eq!(fs::read(&target).unwrap(), data.files()[0].bytes);
        assert!(dir.join(data.files()[0].path).exists());
    }

    #[test]
    fn materialize_leaves_no_temporary_files_behind() {
        let tmp = tempfile::tempdir().unwrap();
        let data = (REGISTRY[0].generate)();
        let dir = tmp.path().join("data");
        materialize(&data, &dir, false).unwrap();

        let strays: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.contains(".tmp."))
            .collect();
        assert!(strays.is_empty(), "temporary files left behind: {strays:?}");
    }
}
