pipeline:
  name: bench-streaming-simple

nodes:
  - type: source
    name: source
    config:
      name: source
      type: csv
      path: bench://input.csv
      options:
        has_header: true
      schema:
        - { name: f0, type: string }
        - { name: f1, type: string }
        - { name: f2, type: string }

  - type: transform
    name: compute
    input: source
    config:
      cxl: |
        emit out = f0 + f2

  - type: output
    name: sink
    input: compute
    config:
      name: sink
      type: csv
      path: bench://output.csv
      include_unmapped: true
